### PR TITLE
Basic UI

### PR DESCRIPTION
**Pull request by principles31**
# Create a mair.rb file that will serve as a console app entry-point:

> In this pull **PR**, the following were implemented as the project requirement as group
- Created the main.rb file that will serve as your console app entry point
- Present the user with a list of options to perform.
- Added the app.rb file and the options file to prepare for the next functionality

### CODE REVIEW

**Review by BouaikIlham — CHANGES_REQUESTED** [review]
Hi @principles31 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

- [x] your branch has a conflict please fix it

**Comment by principles31** [comment]
@BouaikIlham Thanks for the feedback

**Comment by principles31** [comment]
-The changes requested to the regards of the conflict has been resolved.

**Review by BouaikIlham — APPROVED** [review]
Your project is complete!  There is nothing else to say other than... it's time to merge it 👍 👍 😄 👏 

Congratulations! 🎉 🎉 🎉 
comp-2
Cheers and Happy coding!👏👏👏

**Comment by principles31** [comment]
@BouaikIlham Thank you

**Pull request merged**
